name: mongo-sharding

services:

  configSrv:
    image: mongo:8.0.3
    container_name: configSrv
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.12
    volumes:
      - db-data:/data/db
      - config-data:/data/configdb
    command: [ "--configsvr", "--replSet", "config_server", "--bind_ip_all", "--port", "27017" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongo-shard-1:
    container_name: mongo-shard-1
    image: mongo:8.0.3
    restart: unless-stopped
    ports:
      - "27018:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.2
    volumes:
      - mongo-shard-1-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27017" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongo-shard-2:
    container_name: mongo-shard-2
    image: mongo:8.0.3
    restart: unless-stopped
    ports:
      - "27019:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.3
    volumes:
      - mongo-shard-2-data:/data/db
    command: [ "--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27017" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s

  mongos_router:
    container_name: mongos_router
    image: mongo:8.0.3
    restart: unless-stopped
    ports:
      - "27021:27021"
    depends_on:
      - configSrv
    networks:
      app-network:
        ipv4_address: 173.17.0.5
    command: [ "mongos", "--configdb", "config_server/configSrv:27017", "--bind_ip_all", "--port", "27021" ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]

  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - configSrv
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27021"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      app-network:
        ipv4_address: 173.17.0.6


networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16


volumes:
  db-data:
  config-data:
  mongo-shard-1-data:
  mongo-shard-2-data:
